## Use this to start the girder/ girder-worker ecosystem

# Use YAML anchors for the common config between both workers
x-worker: &base-worker
  ipc: host
  build:
    context: .
    dockerfile: docker/girder_worker.Dockerfile
  image: kitware/viame-worker:${TAG:-girder-5}
  volumes:
    - addons:/tmp/addons:ro # readonly
  labels:
    - "com.centurylinklabs.watchtower.enable=true"
  depends_on:
    girder:
      condition: service_started
    rabbit:
      condition: service_started

version: "3.8"
services:

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command: >
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entrypoints.web.address=:80
    volumes:
      - "${SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock"
    ports:
      - "8010:80"

  rabbit:
    image: rabbitmq:3.8.14-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST:-default}
      - RABBITMQ_DISTRIBUTED_WORKER=${RABBITMQ_DISTRIBUTED_WORKER:-0}

  mongo:
    image: mongo:5.0
    volumes:
      # Use env config path, default to docker volume
      - ${MONGO_DB_PATH:-mongo_db}:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  girder:
    build:
      context: .
      dockerfile: docker/girder.Dockerfile
    image: kitware/viame-web:${TAG:-girder-5}
    init: true
    command: ["--mode", "production"]
    depends_on:
      - mongo
      - traefik
    volumes:
      - girder_assetstore:/home/assetstore
      # Bind mount nocopy public data
      - type: bind
        source: ${PUBLIC_DATA_PATH:-./docker/girder_data}
        target: /data/public
        read_only: true
    environment:
      - "GIRDER_MONGO_URI=mongodb://mongo:27017/girder"
      - "GIRDER_ADMIN_USER=${GIRDER_ADMIN_USER:-admin}"
      - "GIRDER_ADMIN_PASS=${GIRDER_ADMIN_PASS:-letmein}"
      - "GIRDER_WORKER_BROKER=${GIRDER_WORKER_BROKER:-amqp://guest:guest@rabbit/default}"
      - "GIRDER_WORKER_BACKEND=${GIRDER_WORKER_BACKEND:-rpc://guest:guest@localhost/}"
      - "GIRDER_SETTING_WORKER_API_URL=${GIRDER_SETTING_WORKER_API_URL:-http://girder:8080/api/v1}"
      - "GIRDER_STATIC_ROOT_DIR=/opt/dive/clients/girder"
      - "GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379"

      # Rabbitmq management variables
      - "RABBITMQ_MANAGEMENT_USERNAME=${RABBITMQ_MANAGEMENT_USERNAME:-guest}"
      - "RABBITMQ_MANAGEMENT_PASSWORD=${RABBITMQ_MANAGEMENT_PASSWORD:-guest}"
      - "RABBITMQ_MANAGEMENT_VHOST=${RABBITMQ_MANAGEMENT_VHOST:-default}"
      - "RABBITMQ_MANAGEMENT_URL=${RABBITMQ_MANAGEMENT_URL:-http://rabbit:15672/}"
      - "RABBITMQ_MANAGEMENT_BROKER_URL_TEMPLATE=${RABBITMQ_MANAGEMENT_BROKER_URL_TEMPLATE}"
      - "WATCHTOWER_API_TOKEN=${WATCHTOWER_API_TOKEN:-mytoken}"
    labels:
      # REMOVING WEEKLY UPDATE
      # - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.services.girder-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.girder-rtr.entrypoints=web"
      - "traefik.http.routers.girder-rtr.rule=HostRegexp(`{catchall:.*}`)"

  # Worker for misc non gpu-bound tasks
  girder_worker_default:
    # Merge base-worker object with this config
    << : *base-worker
    deploy: {}
    volumes:
      # readwrite because this worker does addon updates
      - addons:/tmp/addons:rw
    environment:
      - "WORKER_WATCHING_QUEUES=celery,local"
      - "WORKER_CONCURRENCY=${DEFAULT_WORKER_CONCURRENCY:-3}"
      - "GIRDER_WORKER_BROKER=${GIRDER_WORKER_BROKER:-amqp://guest:guest@rabbit/default}"
      - "GIRDER_WORKER_BACKEND=${GIRDER_WORKER_BACKEND:-rpc://guest:guest@localhost/}"
      - "GIRDER_SETTING_WORKER_API_URL=${GIRDER_SETTING_WORKER_API_URL:-http://girder:8080/api/v1}"

  girder_worker_pipelines:
    # Merge base-worker object with this config
    << : *base-worker
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

    environment:
      - "WORKER_WATCHING_QUEUES=pipelines"
      - "WORKER_CONCURRENCY=${PIPELINE_WORKER_CONCURRENCY:-1}"
      - "WORKER_GPU_UUID=${PIPELINE_GPU_UUID}"
      - "GIRDER_WORKER_BROKER=${GIRDER_WORKER_BROKER:-amqp://guest:guest@rabbit/default}"
      - "GIRDER_WORKER_BACKEND=${GIRDER_WORKER_BACKEND:-rpc://guest:guest@localhost/}"
      - "GIRDER_SETTING_WORKER_API_URL=${GIRDER_SETTING_WORKER_API_URL:-http://girder:8080/api/v1}"
      - "GIRDER_MONGO_URI=mongodb://mongodb:27017/girder"
      - "GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379"


  girder_worker_training:
    # Merge base-worker object with this config
    << : *base-worker
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    environment:
      - "WORKER_WATCHING_QUEUES=training"
      - "WORKER_CONCURRENCY=${TRAINING_WORKER_CONCURRENCY:-1}"
      - "WORKER_GPU_UUID=${TRAINING_GPU_UUID}"
      - "GIRDER_WORKER_BROKER=${GIRDER_WORKER_BROKER:-amqp://guest:guest@rabbit/default}"
      - "GIRDER_WORKER_BACKEND=${GIRDER_WORKER_BACKEND:-rpc://guest:guest@localhost/}"
      - "GIRDER_SETTING_WORKER_API_URL=${GIRDER_SETTING_WORKER_API_URL:-http://girder:8080/api/v1}"


volumes:
  addons:
  mongo_db:
  girder_assetstore:
  redis_data:
