
site_name: DIVE
site_url: https://kitware.github.io/dive
site_description: Documentation for DIVE
site_author: Kitware

repo_url: https://github.com/Kitware/dive

theme:
  name: material
  highlightjs: true
  icon:
    logo: fontawesome/solid/fish

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Web Version: Getting-Started.md
  - Desktop Version: Dive-Desktop.md
  - Annotation Quickstart: Annotation-QuickStart.md
  - Pipeline Docs: Pipeline-Documentation.md
  - User Interface Guide:
    - Introduction: Annotation-User-Interface-Overview.md
    - Navigation Bar: UI-Navigation-Bar.md
    - Edit Bar: UI-Edit-Bar.md
    - Annotation View: UI-Annotation-View.md
    - Type List: UI-Type-List.md
    - Track List: UI-Track-List.md
    - Sharing: UI-Sharing.md
    - Interpolation: UI-Interpolation.md
    - Downloading Data: UI-Downloading-Data.md
    - Attributes: Attributes.md
  - Concepts and Definitions: Definitions.md
  - Mouse and Keyboard Shortcuts: Mouse-Keyboard-Shortcuts.md
  - Advanced features:
    - Custom Pipeline Upload: Pipeline-Upload.md
    - Command Line Tools: Command-Line-Tools.md
    - Server Operator Guide: Server-Operator.md

google_analytics:
  - UA-6042509-43
  - auto
