## Use this to start the girder/ girder-worker ecosystem

# Use YAML anchors for the common config between both workers
x-worker: &base-worker
  runtime: ${WORKER_RUNTIME}
  ipc: host
  build:
    context: ../
    dockerfile: docker/girder_worker.Dockerfile
  image: kitware/viame-worker:${TAG:-latest}
  depends_on:
    girder:
        condition: service_healthy
    rabbit:
        condition: service_started

version: "2.4"
services:

  rabbit:
    image: rabbitmq:management

  mongo:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  girder:
    build:
      context: ../
      dockerfile: docker/girder.Dockerfile
    image: kitware/viame-web:${TAG:-latest}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 5s
        timeout: 5s
        retries: 5
    depends_on:
      - mongo
    ports:
      - "8010:8080"
    volumes:
      - girder_assetstore:/home/assetstore
      # Mount pipeline directory from girder_worker
      - pipelines:${VIAME_PIPELINES_PATH}:ro
      - type: bind
        source: ${PUBLIC_DATA_PATH}
        target: /data/public
        read_only: true
        volume:
          nocopy: true
    environment:
      - VIAME_PIPELINES_PATH=${VIAME_PIPELINES_PATH}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_ADMIN_USER=${GIRDER_ADMIN_USER}
      - GIRDER_ADMIN_PASS=${GIRDER_ADMIN_PASS}

  # Worker for misc non gpu-bound tasks
  girder_worker_default:
    # Merge base-worker object with this config
    << : *base-worker
    environment:
      - WORKER_WATCHING_QUEUES=celery

  girder_worker_pipelines:
    # Merge base-worker object with this config
    << : *base-worker
    volumes:
      # Exposes pipeline directory to girder so it can see what pipelines are available.
      - pipelines:${VIAME_PIPELINES_PATH}:ro
    environment:
      - WORKER_WATCHING_QUEUES=pipelines
      - WORKER_CONCURRENCY=${PIPELINE_WORKER_CONCURRENCY:-1}
      - WORKER_GPU_UUID=${PIPELINE_GPU_UUID}
      - VIAME_PIPELINES_PATH=${VIAME_PIPELINES_PATH}

  girder_worker_training:
    # Merge base-worker object with this config
    << : *base-worker
    environment:
      - WORKER_WATCHING_QUEUES=training
      - WORKER_CONCURRENCY=${TRAINING_WORKER_CONCURRENCY:-1}
      - WORKER_GPU_UUID=${TRAINING_GPU_UUID}
      - VIAME_PIPELINES_PATH=${VIAME_PIPELINES_PATH}

volumes:
  pipelines:
  mongo_db:
  girder_assetstore:
