
version: "2.4"
services:

  rabbit:
    # expose web console
    ports:
      - "15672:15672"

  girder:
    volumes:
      - ../docker/provision:/home/provision
      - ../server:/home/viame_girder
    entrypoint: ["/home/provision/girder_entrypoint_dev.sh"]

  girder_worker:
    volumes:
      - ../server:/home/viame_girder

  mc:
    image: mongo
    command: ["mongo", "mongodb://mongo:27017/girder"]
