## Use this to start the girder/ girder-worker ecosystem

# Use YAML anchors for the common config between both workers
x-worker: &base-worker
  runtime: ${WORKER_RUNTIME}
  ipc: host
  build:
    context: ../
    dockerfile: docker/girder_worker.Dockerfile
  image: kitware/viame-worker:${TAG:-latest}
  depends_on:
    girder:
        condition: service_healthy
    rabbit:
        condition: service_started

version: "2.4"
services:

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command: >
      --api.insecure=true
      --serversTransport.insecureSkipVerify=true
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entrypoints.web.address=:80
    labels:
      - "traefik.enable=true"
    volumes:
      - ${SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    ports:
      - "8010:80"

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}

  mongo:
    image: mongo:latest
    volumes:
      # Bind mount assetstore from local directory
      # - ${DIVE_GIRDER_MONGO_DATA:-girder_data/mongo}:/data/db
      - mongo_db:/data/db

  girder:
    build:
      context: ../
      dockerfile: docker/girder.Dockerfile
    image: kitware/viame-web:${TAG:-latest}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 5s
        timeout: 5s
        retries: 5
    depends_on:
      - mongo
    volumes:
      # Bind mount assetstore from local directory
      # - ${DIVE_GIRDER_ASSETSTORE:-girder_data/assetstore}:/home/assetstore
      - girder_assetstore:/home/assetstore
      # Bind mount nocopy public data
      - type: bind
        source: ${PUBLIC_DATA_PATH:-girder_data}
        target: /data/public
        read_only: true
        volume:
          nocopy: true
    environment:
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_ADMIN_USER=${GIRDER_ADMIN_USER}
      - GIRDER_ADMIN_PASS=${GIRDER_ADMIN_PASS}
      - "CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit/"
    labels:
      - traefik.enable=true
      - traefik.http.services.girder-svc.loadbalancer.server.port=8080
      - traefik.http.routers.girder-rtr.entrypoints=web
      - traefik.http.routers.girder-rtr.rule=HostRegexp(`{catchall:.*}`)

  # Worker for misc non gpu-bound tasks
  girder_worker_default:
    # Merge base-worker object with this config
    << : *base-worker
    volumes:
      # readwrite because this worker does addon updates
      - addons:/tmp/addons:rw
    environment:
      - WORKER_WATCHING_QUEUES=celery
      - "CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit/"

  girder_worker_pipelines:
    # Merge base-worker object with this config
    << : *base-worker
    volumes:
      - addons:/tmp/addons:ro # readonly
    environment:
      - WORKER_WATCHING_QUEUES=pipelines
      - WORKER_CONCURRENCY=${PIPELINE_WORKER_CONCURRENCY:-1}
      - WORKER_GPU_UUID=${PIPELINE_GPU_UUID}
      - "CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit/"

  girder_worker_training:
    # Merge base-worker object with this config
    << : *base-worker
    volumes:
      - addons:/tmp/addons:ro # readonly
    environment:
      - WORKER_WATCHING_QUEUES=training
      - WORKER_CONCURRENCY=${TRAINING_WORKER_CONCURRENCY:-1}
      - WORKER_GPU_UUID=${TRAINING_GPU_UUID}
      - "CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit/"

volumes:
  addons:
  mongo_db:
  girder_assetstore:
