## Use this to start the girder/ girder-worker ecosystem
version: "2.4"
services:

  rabbit:
    image: rabbitmq:management

  mongo:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  girder:
    build:
      context: ../
      dockerfile: docker/girder.Dockerfile
    image: kitware/viame-web:${TAG:-latest}
    depends_on:
      - mongo
      - girder_worker
    ports:
      - "8010:8080"
    volumes:
      - girder_assetstore:/home/assetstore
      # Mount pipeline directory from girder_worker
      - pipelines:${VIAME_PIPELINES_PATH}:ro
      - type: bind
        source: ${PUBLIC_DATA_PATH}
        target: /data/public
        read_only: true
        volume:
          nocopy: true
    environment:
      - VIAME_PIPELINES_PATH=${VIAME_PIPELINES_PATH}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_ADMIN_USER=${GIRDER_ADMIN_USER}
      - GIRDER_ADMIN_PASS=${GIRDER_ADMIN_PASS}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit/
      - BROKER_CONNECTION_TIMEOUT=2

  girder_worker:
    runtime: 'nvidia'
    build:
      context: ../
      dockerfile: docker/girder_worker.Dockerfile
    image: kitware/viame-worker:${TAG:-latest}
    volumes:
      # Exposes pipeline directory to girder so it can see what pipelines are available.
      - pipelines:${VIAME_PIPELINES_PATH}:ro
    depends_on:
      - rabbit
    environment:
      - VIAME_PIPELINES_PATH=${VIAME_PIPELINES_PATH}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit/
      - BROKER_CONNECTION_TIMEOUT=2

volumes:
  pipelines:
  mongo_db:
  girder_assetstore:
