version: "2.4"
services:
  # Worker for misc non gpu-bound tasks
  worker:
    runtime: ${WORKER_RUNTIME}
    ipc: host
    image: kitware/viame-worker:${TAG:-latest}
    volumes:
      # readwrite because this worker does addon updates
      - ${ADDON_PATH}:/tmp/addons:rw
    environment:
      - WORKER_WATCHING_QUEUES=${WORKER_WATCHING_QUEUES}
      - "CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}/"
